kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: rest-api-hpa
  namespace: rest-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rest-api-deployment
  minReplicas: 1
  maxReplicas: 10
  # targetCPUUtilizationPercentage: 50 => old way to do it
  metrics:
  # Pods and Object metrics are considered custom metrics and may have names which are cluster specific, and require a more advanced cluster monitoring setup.
  # They only support a target type of AverageValue and are averaged together across Pods and compared with a target value to determine the replica count
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: main-route
      target:
        type: Value
        value: 10k